# Generated by Django 4.2.16 on 2026-04-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.CharField(max_length=600)),
                ('confidence', models.FloatField(default=0.0)),
                ('peak_hour', models.PositiveSmallIntegerField(default=0)),
                ('deviation_pct', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_suggestions', to='menu.menuitem')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_quantity', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='menu.menuitem')),
            ],
            options={
                'ordering': ['-forecast_date', '-predicted_quantity'],
                'unique_together': {('menu_item', 'forecast_date')},
            },
        ),
    ]
